package cflow;

/* Generated By:JJTree: Do not edit this line. ASTAny.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAny extends SimpleNode {
  public ASTAny(int id) {
    super(id);
  }

  public ASTAny(RegexParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b8f07cf89ffd72e957b992ecd56b8c41 (do not edit this line) */
