package cflow;

/* Generated By:JJTree: Do not edit this line. ASTBracket.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBracket extends SimpleNode {
  public ASTBracket(int id) {
    super(id);
  }

  public ASTBracket(RegexParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=77c150cbb9e0f06b3299a02fb9e2d2f9 (do not edit this line) */
