package cflow;

/* Generated By:JJTree: Do not edit this line. ASTBegin.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBegin extends SimpleNode {
  public ASTBegin(int id) {
    super(id);
  }

  public ASTBegin(RegexParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=36a442b15741eac5d5f31f8d30a6936f (do not edit this line) */
