package cflow;

/* Generated By:JJTree: Do not edit this line. ASTBracketElements.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBracketElements extends SimpleNode {
  public ASTBracketElements(int id) {
    super(id);
  }

  public ASTBracketElements(RegexParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6351a82975b4c5377ceb2e6b99a4c65b (do not edit this line) */
