
package cflow;
/* Generated By:JJTree: Do not edit this line. ASTBracketElems.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBracketElems extends SimpleNode {
  public ASTBracketElems(int id) {
    super(id);
  }

  public ASTBracketElems(RegexParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5d436af7463cfa6fe73260edbb10d3a9 (do not edit this line) */
