package cflow;

/* Generated By:JJTree: Do not edit this line. ASTBracketC.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBracketC extends SimpleNode {
  public ASTBracketC(int id) {
    super(id);
  }

  public ASTBracketC(RegexParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bd50b0e029272d76021da277210922d7 (do not edit this line) */
