package cflow;
/* Generated By:JJTree: Do not edit this line. ASTChar.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTChar extends SimpleNode {
  public ASTChar(int id) {
    super(id);
  }

  public ASTChar(RegexParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6af27e87fcec0f09441962fa05a648f4 (do not edit this line) */
