package cflow;
/* Generated By:JJTree: Do not edit this line. ASTEnd.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEnd extends SimpleNode {
  public ASTEnd(int id) {
    super(id);
  }

  public ASTEnd(RegexParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4a08021878b51370047e09720432b51d (do not edit this line) */
