package cflow;
/* Generated By:JJTree: Do not edit this line. ASTnbracket.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTnbracket extends SimpleNode {
  public ASTnbracket(int id) {
    super(id);
  }

  public ASTnbracket(RegexParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e3f25a6cc78f723752f4c945bac38779 (do not edit this line) */
