package cflow;
/* Generated By:JJTree: Do not edit this line. ASTroot.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTroot extends SimpleNode {
  public ASTroot(int id) {
    super(id);
  }

  public ASTroot(RegexParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b35067ee9cdab045d4d47d6cb7ebbbb1 (do not edit this line) */
