/* Generated By:JJTree&JavaCC: Do not edit this line. RegexParserConstants.java */
package cflow;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RegexParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CHAR = 4;
  /** RegularExpression Id. */
  int LETTER = 5;
  /** RegularExpression Id. */
  int NUMBER = 6;
  /** RegularExpression Id. */
  int ANYTHING = 7;
  /** RegularExpression Id. */
  int MULTIPLICITY = 8;
  /** RegularExpression Id. */
  int SPECIFYOCURR1 = 9;
  /** RegularExpression Id. */
  int SPECIFYOCURR2 = 10;
  /** RegularExpression Id. */
  int BETWEEN = 11;
  /** RegularExpression Id. */
  int PIPE = 12;
  /** RegularExpression Id. */
  int NL = 13;
  /** RegularExpression Id. */
  int CARET = 14;
  /** RegularExpression Id. */
  int LASTELEM = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<CHAR>",
    "<LETTER>",
    "<NUMBER>",
    "\".\"",
    "<MULTIPLICITY>",
    "<SPECIFYOCURR1>",
    "<SPECIFYOCURR2>",
    "<BETWEEN>",
    "\"|\"",
    "\"\\n\"",
    "\"^\"",
    "\"$\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"[^\"",
  };

}
