/* Generated By:JavaCC: Do not edit this line. RegexParserTreeConstants.java Version 5.0 */
package cflow;

public interface RegexParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTBEGIN = 1;
  public int JJTEND = 2;
  public int JJTVOID = 3;
  public int JJTOR = 4;
  public int JJTMULT = 5;
  public int JJTAND = 6;
  public int JJTCHAR = 7;
  public int JJTANY = 8;
  public int JJTBRACKET = 9;
  public int JJTBRACKETC = 10;
  public int JJTBRACKETELEMS = 11;


  public String[] jjtNodeName = {
    "root",
    "Begin",
    "End",
    "void",
    "OR",
    "Mult",
    "AND",
    "Char",
    "Any",
    "Bracket",
    "BracketC",
    "BracketElems",
  };
}
/* JavaCC - OriginalChecksum=08bc7d7434d5aabe648a9feef0f1526e (do not edit this line) */
